#!/usr/bin/bash
docker run --rm -ti \
    -p 20:20 -p 21:21 -p 21100-21110:21100-21110 \
    -e FTP_USER=user -e FTP_PASS=pass \
    -e PASV_ADDRESS=127.0.0.1 -e PASV_MIN_PORT=21100 -e PASV_MAX_PORT=21110 \
    --net ftpnet --ip 10.1.1.100 \
    --name vsftpd fauria/vsftpd
